# -*- mode: ruby -*-
# vi: set ft=ruby :
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.define "a01" do |a01|
    a01.vm.box = "matthewmengel/usq-bullseye64"
    a01.vm.hostname = 'a01'

    a01.vm.network :private_network, ip: "192.168.56.121"
    a01.vm.network :forwarded_port, guest: 22, host: 10221, id: "ssh"

    a01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "a01"
    end

    a01.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/all/site.yml"
      ansible.compatibility_mode = "2.0"
    end
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  # config.vm.provision "ansible" do |ansible|
    # ansible.playbook = "../ansible/site.yml"
    # ansible.compatibility_mode = "2.0"
  # end
end