---
- name: Provision VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: debian
  tasks:
    - import_tasks: ./usq-packages.yml
    - import_tasks: ./adduser.yml
    - import_tasks: ./sshconf.yml
  handlers:
    - import_tasks: handlers/restart_ssh.yml
    - import_tasks: handlers/restart_rsyslog.yml
